import { GoogleSpreadsheet } from "google-spreadsheet";

// Initialize the sheet - doc ID is the long id in the sheets URL
const doc = new GoogleSpreadsheet(
  "1lsPIpLGWYiH2zA0MxKdI0asrRc4l9arHJbzxSOX4twU"
);

const queries = {
  SnarkyJS: "path:/(^|/)package.json$/ snarkyjs",
  Circom: '"component main" extension:circom',
  Leo: '"aleo" filename:program.json',
  Noir: '"noir-lang" "aztec_backend" filename:package.json',
  Cairo: "lang starknet extension:cairo",
  RISC0: 'dependencies "risc0-zkp" filename:Cargo.toml',
  ZoKrates: "zokrates",
  Gnark: "gnark",
};

const getNumberOfResults = (query) =>
  fetch("https://cs.github.com/api/count?q=" + query, {
    cookies: process.env.GITHUB_COOKIE,
    method: "GET",
  }).then((res) => res.json().then((data) => data.count));

export default async function handler(req, res) {
  // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
  await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
    private_key: process.env.GOOGLE_PRIVATE_KEY.split(String.raw`\n`).join(
      "\n"
    ),
  });

  // Fix this + queries object? How should people add or alter queries?
  const adoptionStats = {
    UnixTime: Date.now(),
    SnarkyJS: await getNumberOfResults(query.SnarkyJS),
    Circom: 1385,
    Leo: 96,
    Noir: 38,
    Cairo: 10925,
    RISC0: 116,
    ZoKrates: 604,
    Gnark: 1232,
  };

  await doc.loadInfo(); // loads sheets
  const sheet = doc.sheetsByIndex[0]; // the first sheet

  const newRow = await sheet.addRow({
    ...adoptionStats,
  });

  res.status(200).json(adoptionStats);
}
