import { GoogleSpreadsheet } from "google-spreadsheet";

// Initialize the sheet - doc ID is the long id in the sheets URL
const doc = new GoogleSpreadsheet(
  "1lsPIpLGWYiH2zA0MxKdI0asrRc4l9arHJbzxSOX4twU"
);

const queries = {
  SnarkyJS: '"keywords" "mina zkapp": filename:package.json',
  Circom: '"component main" extension:circom',
  Leo: '"aleo" filename:program.json',
  Noir: '"noir-lang" "aztec_backend" filename:package.json',
  Cairo: "lang starknet extension:cairo",
  RISC0: 'dependencies "risc0-zkp" filename:Cargo.toml',
  ZoKrates: "zokrates",
  Gnark: "gnark",
};

const githubHeaders = new Headers({
  Accept: "application/vnd.github+json",
  Authorization: "Bearer " + process.env.GITHUB_TOKEN,
  "X-GitHub-Api-Version": "2022-11-28",
});

const getNumberOfResults = (query) =>
  fetch("https://api.github.com/search/code?per_page=1&q=" + query, {
    headers: githubHeaders,
    method: "GET",
  }).then((res) => res.json().then((data) => data.total_count));

export default async function handler(req, res) {
  // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
  await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
    private_key: process.env.GOOGLE_PRIVATE_KEY.split(String.raw`\n`).join(
      "\n"
    ),
  });

  // Fix this + queries object? How should people add or alter queries?
  const adoptionStats = {
    UnixTime: Date.now(),
    SnarkyJS: 244,
    Circom: 1325,
    Leo: 115,
    Noir: 38,
    Cairo: 10900,
    RISC0: 116,
    ZoKrates: 19,
    Gnark: 1211,
  };

  await doc.loadInfo(); // loads sheets
  const sheet = doc.sheetsByIndex[0]; // the first sheet

  const newRow = await sheet.addRow({
    ...adoptionStats,
  });

  res.status(200).json(adoptionStats);
}
